export function Footer() {
  return (
    <div className="mt-auto border-t pt-4 text-sm">
      <div className="flex justify-between">
        <div>
          <p>Prepared By</p>

          <div className="mt-8 w-32 border-b" />
        </div>

        <div>
          <p>Approved By</p>

          <div className="mt-8 w-32 border-b" />
        </div>
      </div>

      <div className="mt-5 text-center text-xs text-muted-foreground">
        Generated by CatLium Voucher Generator
        <br />© CatLium Technologies
      </div>
    </div>
  )
}
